apiVersion: v1
kind: Service
metadata:
  name: appserver-ingress-svc
  labels:
    app: appserver-ingress
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    name: https
  type: NodePort
  selector:
    app: appserver-ingress
