apiVersion: v1
kind: ReplicationController
metadata:
  name: appserver-ingress-rc
  labels:
    app: appserver-ingress
spec:
  replicas: 1
  selector:
    app: appserver-ingress
  template:
    metadata:
      labels:
        app: appserver-ingress
    spec:
      containers:
      - image: achackery/appserver-ingress:1.0.11
        imagePullPolicy: Always
        name: appserver-ingress
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # Uncomment the lines below to enable extensive logging and/or customization of
        # NGINX configuration with configmaps
        args:
         #- -v=3
          - -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
          - -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
