apiVersion: v1
kind: ReplicationController
metadata:
  name: dotnet-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
      - name: dotnet
        image: achackery/dotnet-asi:1.0.1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 400m
