kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  http-snippets: | # No default. Pipe is used for multiple line snippets.
    js_include conf.d/app_router.js;                     # Load JavaScript code from here
    js_set     $platformType getPlatformType;            # Fill variable from JS function
