apiVersion: v1
kind: ReplicationController
metadata:
  name: webapi-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: achackery/webapi-asi
        ports:
        - containerPort: 80
